#!/bin/bash
#SBATCH -N 1
#SBATCH -J ax_compile
#SBATCH -A hpc-prf-aafpga
#SBATCH -p fpgasyn
#SBATCH -t 24:00:00
#SBATCH --mail-type all
#SBATCH --mail-user makarp@kth.se
#SBATCH --mem=90000MB
module load nalla_pcie
module load intelFPGA_pro 

aoc -v -report ax.cl -global-ring -duplicate-ring
